### ISSUE TITLE
Any tips for rebuilding noble-winrt?

### ISSUE THREAD

**Issue by ELundby45** [Timeular/noble-winrt#14]
Thank you and Timeular for working on noble-winrt, I'm very hopeful this gets merged into noble soon.

I'm facing similar struggles to issue #11, with the exception that I'm trying to build for nw.js. Rather than having you specify every possible version of electron and nw.js in appveyor, do you have any tips for the correct dev setup for building noble-winrt?

I have Visual Studio 2017 installed along with all of the build tools but am facing tons of errors when trying to rebuild (most along the lines of `\noble-winrt\src\napi_winrt.h(7): error C2065: 'UUID': undeclared identifier`)

I've tried running:
- `prebuild -t 0.34.5 -r node-webkit`
- `nw-gyp rebuild --target=0.34.5 --arch=ia32`
- `node-gyp rebuild`
- `prebuild -t 6.14.4 -t 8.12.0 -r node`

All producing the same errors ([error_log.log](https://github.com/Timeular/noble-winrt/files/2646524/error_log.log))

**Comment by geovie** [comment]
Hi @ELundby45,
Have you installed the matching `Windows 10 SDK` (at least build 10.0.17134.0)? If yes, which version of the SDK are you using?   
Which version of Visual Studio 2017 are you using?

Maybe including rpc.h (`#include <rpc.h>`) in `napi_winrt.h` could solve the problem...

**Comment by ELundby45** [comment]
@geovie I have installed the SDKs and it is trying to use 10.0.17763.0 (according to `node-gyp configure --verbose`)

Visual Studio 2017 v15.9.3

Including rpc.h did remove some of the errors, but still getting quite a few. Do you mind sharing which Visual Studio version and SDK version have worked for you? I can try downgrading. 

[error_log.log](https://github.com/Timeular/noble-winrt/files/2649583/error_log.log)

**Comment by geovie** [comment]
Looks like the API changed between `10.0.17134.0` and `10.0.17763.0` (it uses now `winrt::guid` instead of `GUID`/`UUID` ). For now it should work if you downgrade to SDK `10.0.17134.0`, I will update the code later this week

**Comment by ELundby45** [comment]
Got it working. Thank you very much!
