### ISSUE TITLE
Is it possible to manually add a service/char to the winrt cache? 

### ISSUE THREAD

**Issue by pursual** [Timeular/noble-winrt#20]
Noble has a caching mechanism for services/chars. See the examples folder for `cache-gatt`.
For a binding to support this, it needs to have an addService and addCharacteristic method. 

Do we know if it would be possible to create a windows `GattDeviceService` or `GattCharacteristic` manually, and inject it into `cachedServices/Chars`?

I looked at service, and the noble representation is
``` 
 {
      "startHandle": 13,
      "endHandle": 21,
      "uuid": "a3e68a834c4d4778bd0a829fb434a7a1"
}
```

I was unable to determine how I would create this manually from looking at: https://docs.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.genericattributeprofile.gattdeviceservice?view=winrt-19041

I assume you would need to call some GattDeviceService constructor, and then somehow set the uuid and handles? Sorry, C++ is not my forte.

**Comment by geovie** [comment]
Hi, we already cache services and characteristics after the first access see [here](https://github.com/Timeular/noble-winrt/blob/master/src/peripheral_winrt.cc#L84-L133)

`PeripheralWinrt::GetService` will first check if the service is already in the cache and if not it will ask windows to get the service 'from the device' and cache it

**Comment by pursual** [comment]
Yes, I'm referring to manually adding to the cache, without any access at all to the device. This is useful in situations where you are always connecting to the same type of device, and want to import the services from a file, as opposed to having to discover them. It's faster.

**Comment by geovie** [comment]
Windows takes care of the services, what you could use is [GetGattServicesForUuidAsync](https://docs.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.bluetoothledevice.getgattservicesforuuidasync?view=winrt-19041) with `BluetoothCacheMode = Cached` to try to get the service without asking the device and if that fails try it with `BluetoothCacheMode = Uncached`

**Comment by pursual** [comment]
This is a different concept. This is telling winrt what services exist, not asking it. Please look at the example code in noble.

**Comment by pursual** [comment]
Sorry, its in the @anabdonware fork, which is probably the most popular now. 
https://github.com/abandonware/noble/tree/master/examples

**Comment by pursual** [comment]
Closing, this is probably not possible with any binding other than the hci.
