### ISSUE TITLE
Connectable value in noble is false, when other bindings report true for same advertisement? 

### ISSUE THREAD

**Issue by tony-gutierrez** [Timeular/noble-winrt#22]
I am not sure how the noble connectable flag on an advertisement is controlled, but the winrt bindings seem to report false?

**Comment by tony-gutierrez** [comment]
It looks like only the connectable value from the first advertised packet is ever used. It does not get updated once added to the cache. 

Am I incorrect in thinking each advert needs to be evaluated for connectable? 

Noticed that noble-uwp has the same bug.

**Comment by pursual** [comment]
https://github.com/Timeular/noble-winrt/pull/23

**Comment by tony-gutierrez** [comment]
Fixed in #23 , Hopefully gets merged. 

There are a lot of good updates at https://github.com/fido-alliance/noble-winrt as well, wish we could get them integrated.
