### ISSUE TITLE
Is there a need for the local cache? 

### ISSUE THREAD

**Issue by tony-gutierrez** [Timeular/noble-winrt#24]
Windows has its own cache of services and chars, so do we really need the local cache that winrt currently has? 

The local cache is not currently populated by DiscoverServices, so subsequent calls for a single service or char will hit windows again, windows will serve from its ble cache, and then we add to local cache. 

It seems like the local cache could be eliminated.

**Comment by geovie** [comment]
Actually the way it's implement currently is correct, as all services need first to be [discovered](https://github.com/Timeular/noble-winrt/blob/master/src/ble_manager.cc#L264) they should already be in cache once we request one.

**Comment by tony-gutierrez** [comment]
Yeah, that is what happens. On second discovery, it misses local cache, and hits windows. On 3rd it would probably hit the local cache. I am just thinking we don't need the local cache. We might need to track chars like you said, but I don't think the local cache check before reading a service is not needed.

**Comment by pursual** [comment]
There is now expanded information on the cache at the MS url linked above.

**Comment by pursual** [comment]
Was able to get a good perf improvement in my version by using Cached mode, in addition to not trashing the local cache on disconnect. Have not tested eliminating the local cache and just relying on windows, but seems like a logical next step.

**Comment by tony-gutierrez** [comment]
Was able to get a good perf improvement in my version by using Cached mode, in addition to not trashing the local cache on disconnect. Have not tested eliminating the local cache and just relying on windows, but seems like a logical next step.

**Comment by geovie** [comment]
As far as I can see we're already using `BluetoothCacheMode::Cached` everywhere. If we can rely on the windows caching then we could definitely remove our custom cache, after all it'll be less code and less of a chance to get out of sync with the device.

**Comment by tony-gutierrez** [comment]
Ah, somehow my code started with some Uncached, from a fork I guess. I'll be in touch if I get a chance to remove local cache.

**Comment by tony-gutierrez** [comment]
Removing cachedServices seems to cause 2 problems:

1. You lose the ability to maintain cachedServices during disconnect, which for my use case allows for rapid retries of a failed procedure.
2. Notify seems to break, it stops announcing characteristic value changes. 

Closing this for now.
