### ISSUE TITLE
manufacturerData is null

### ISSUE THREAD

**Issue by SamDecrock** [Timeular/noble-winrt#6]
Hi,

I'm trying your take on noble because I had some annoying delays with the noble-uwp library.
I'm working with RFDuino's en they can contain some extra data in the manufacturerData. However, using your library, manufacturerData is null:

```
{ localName: 'SMASHY',
  txPowerLevel: 0,
  manufacturerData: null,
  serviceUuids: [ '00002220-0000-1000-8000-00805f9b34fb' ],
  serviceData: [] }

```

With noble-uwp, it's:

```
{ localName: 'SMASHY',
  txPowerLevel: 4,
  manufacturerData: <Buffer 00 00 67 72 65 65 6e>,
  serviceUuids: [ '2220' ],
  serviceData: [ { uuid: '2220' } ] }
```

If I can be of any help to debug this, let me know.

**Comment by SamDecrock** [comment]
Nevermind, apparently I installed this module instead of yours: https://github.com/urish/noble-winrt
Are you on npm with this module?

**Comment by jrobeson** [comment]
It's not on npm because the name is already taken.  I'm seeing some delays too as described in https://github.com/Timeular/noble-winrt/issues/7 

I'm seeing some issues with manufacturerData being "" occasionally when it shouldn't be blank.

**Comment by jrobeson** [comment]
@SamDecrock : have you gotten a chance to try it? what have you seen?

**Comment by SamDecrock** [comment]
Sorry, I might not have been clear. `manufacturerData` is there using your library.
I was using the wrong library.

What I am experiencing is tid-bit of delay when sending data from my RFDuino (Arduino like BLE prototyping device) to my pc. But that could be related to my own code as I have it with the original noble too.
